Facebro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('auth/', include('apps.auth_facebro.urls', namespace='auth_facebro')),
    path('base/', include('apps.base_facebro.urls', namespace='base_facebro')),
    path('', include('apps.app_facebro.urls', namespace='app_facebro')),
    path('admin/', admin.site.urls),
]

apps/app_facebro/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'app_facebro'

urlpatterns = [
    path('', views.index, name='index'),
    path('timeline', views.timeline, name='timeline'),
    path('user/<int:user_id>/wall', views.wall, name='wall'),
    path('settings', views.setting, name='setting'),
    path('profile/update', views.profile_update, name='profile_update'),
    path('profile/upload', views.profile_upload, name='profile_upload'),
    path('password/update', views.password_update, name='password_update'),
    path('user/<int:user_id>/post', views.post_create, name='post_create'),
    path('post/<int:post_id>/delete', views.post_delete, name='post_delete'),
    path('user/<int:user_id>/following', views.following, name='following'),
    path('user/<str:email>/follow', views.follow, name='follow'),
    path('user/<str:user_id>/unfollow', views.unfollow, name='unfollow'),
    path('user/<int:user_id>/follower', views.follower, name='follower'),
    path('user/<int:user_id>/photos', views.photo, name='photo'),
    path('photo/create', views.photo_create, name='photo_create'),
    path('photo/<int:photo_id>/delete', views.photo_delete, name='photo_delete'),
    path('search', views.search, name='search'),
    path('results/<str:query>', views.results, name='results'),
    path('comment/<int:post_id>/post', views.comment_post, name='comment_post'),
    path('comment/<int:comment_id>/delete', views.comment_delete, name='comment_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/base_facebro/urls.py
from django.urls import path
from . import views

app_name = 'base_facebro'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

apps/app_facebro/models.py
from django.db import models
from apps.auth_facebro.models import User

class Post(models.Model):
    
    content = models.TextField()

    user = models.ForeignKey(User, related_name='user_post', on_delete=models.CASCADE)
    following = models.ForeignKey(User, related_name='following_post', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def get_comment(self):
        return self.post_comment.all().order_by('created_at')

class Friend(models.Model):

    following = models.ForeignKey(User, related_name='user_following_friend', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_friend', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):

    content = models.CharField(max_length=256)
    
    post = models.ForeignKey(Post, related_name='post_comment', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_comment', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Photo(models.Model):
    
    caption = models.CharField(max_length=128)
    src = models.CharField(max_length=128, unique=True)

    user = models.ForeignKey(User, related_name='user_photo', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/app_facebro/views.py
import os, uuid
from django.shortcuts import render, redirect
from django.contrib import messages

from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage

from django.db.models import Q
from django.http import HttpRequest
from apps.auth_facebro.models import User, Profile
from apps.auth_facebro import utilities as util

from . import models as m

def index(request):
    if 'user_id' in request.session:
        return redirect('app_facebro:wall', user_id=request.session['user_id'])
    
    return render(request, 'app_facebro/index.html')

def timeline(request):
    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')

    try:
        posts = m.Post.objects.filter(Q(following_id=request.session['user_id']) | Q(user_id=request.session['user_id'])).order_by('-created_at')
    except:
        pass

    context = {
        'user': User.objects.get(id=request.session['user_id']),
        'posts': posts
    }

    return render(request, 'app_facebro/timeline.html', context)

def wall(request, user_id):
    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')

    try:

        followed = []

        if 'user_id' in request.session:
            for following in m.Friend.objects.filter(Q(following_id=request.session['user_id']) | Q(user_id=request.session['user_id'])):
                followed.append(following.following_id)

        user = User.objects.get(id=user_id)
        posts = m.Post.objects.filter(Q(user_id=user_id) | Q(following_id=user_id)).order_by('-created_at')

        context = {
            'user' : user,
            'followed' : followed,
            'posts' : posts
        }

    except:

        context = {
            'user' : [],
            'followed' : [],
            'posts' : []
        }

    return render(request, 'app_facebro/wall.html', context)

def comment_post(request, post_id):
    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')

    url = request.META.get('HTTP_REFERER')

    if request.method == 'POST':

        try:
            comment = m.Comment()
            comment.content = request.POST['html_content']
            comment.post_id = post_id
            comment.user_id = request.session['user_id']
            comment.save()
        except:
            pass

    return redirect(url)

def comment_delete(request, comment_id):
    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')

    url = request.META.get('HTTP_REFERER')

    try:
        comment = m.Comment.objects.get(id=comment_id)
        comment.delete()
    except:
        pass

    return redirect(url)

def setting(request):
    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')

    user = User.objects.get(id=request.session['user_id'])
    photos = Profile.objects.filter(user_id=request.session['user_id'])

    context = {
        'user': user,
        'photos': photos
    }

    return render(request, 'app_facebro/setting.html', context)

def profile_upload(request):

    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')

    if request.method == 'POST' and request.FILES['file']:
        
        myfile = request.FILES['file']

        fs = FileSystemStorage()
        filename = fs.save(str(uuid.uuid4())+'.'+myfile.name.split('.')[-1], myfile)
        uploaded_file_url = fs.url(filename)

        try:
            request.session['error'] = ''

            profile = Profile()
            profile.image = uploaded_file_url
            profile.is_active = 1
            profile.user_id = request.session['user_id']
            profile.save()

            request.session['error'] = 'profile_upload'

            messages.error(request, 'Profile photo uploaded')

            return redirect('app_facebro:setting')
        except:
            messages.error(request, 'Profile upload error')

    return redirect('app_facebro:setting')

def profile_update(request):

    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')

    if request.method == 'POST':

        request.session['error'] = ''

        name = request.POST['html_name']
        email = request.POST['html_email']

        errors = []
        errors += util.is_blank('name', name)
        errors += util.is_blank('email', email)

        if not util.EMAIL_REGEX.match(email):
            errors.append('Email formated error')

        for error in errors:
            messages.error(request, error)

        request.session['error'] = 'profile_update'

        if len(errors) == 0:

            try:
            
                user = User.objects.get(id=request.session['user_id'])
                user.name = name
                user.email = email
                user.save()

                request.session['user_id'] = user.id
                request.session['name'] = user.name

                messages.error(request, 'Update profile success')

            except:

                messages.error(request, 'Update profile error')

    return redirect('app_facebro:setting')

def password_update(request):

    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')

    if request.method == 'POST':

        request.session['error'] = ''

        password = request.POST['html_password']
        confirm = request.POST['html_confirm']

        errors = []

        errors += util.is_blank('password', password)
        errors += util.is_blank('confirm', confirm)

        if password != confirm:
            errors.append('Password doesn\'t match')
        if len(password) < 6:
            errors.append('Password too short')

        for error in errors:
            messages.error(request, error)

        request.session['error'] = 'password_update'

        if len(errors) == 0:

            try:
            
                user = User.objects.get(id=request.session['user_id'])
                user.password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
                user.save()

                messages.error(request, 'Update profile success')

            except:

                messages.error(request, 'Update profile error')

    return redirect('app_facebro:setting')

def follower(request, user_id):

    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')

    user = User.objects.get(id=user_id)

    followed = []

    if 'user_id' in request.session:
        for following in m.Friend.objects.filter(user_id=request.session['user_id']):
            followed.append(following.following_id)

    try:
        context = {
            'user': user,
            'followed' : followed,
            'follower' : m.Friend.objects.filter(following_id=user_id)
        }
    except:
        
        context = {
            'user': user,
            'followed' : [],
            'follower' : []
        }

    return render(request, 'app_facebro/follower.html', context)

def following(request, user_id):

    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')

    user = User.objects.get(id=user_id)

    followed = []

    if 'user_id' in request.session:
        for following in m.Friend.objects.filter(user_id=request.session['user_id']):
            followed.append(following.following_id)

    try:
        context = {
            'user': user,
            'followings': m.Friend.objects.filter(user_id=user_id),
            'followed': followed
        }
    except:
        
        context = {
            'user': user,
            'followings': [],
            'followd': []
        }

    return render(request, 'app_facebro/following.html', context)

def follow(request, email):

    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')

    url = request.META.get('HTTP_REFERER')

    try:
        user = User.objects.get(email=email)

        friend = m.Friend()
        friend.following_id = user.id
        friend.user_id = request.session['user_id']
        friend.save()
    except:
        pass

    return redirect(url)

def unfollow(request, user_id):

    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')

    url = request.META.get('HTTP_REFERER')

    try:
        friend = m.Friend.objects.filter(following_id=user_id, user_id=request.session['user_id'])
        friend.delete()
    except:
        pass

    return redirect(url)

def photo(request, user_id):

    followed = []

    if 'user_id' in request.session:
        for following in m.Friend.objects.filter(Q(following_id=request.session['user_id']) | Q(user_id=request.session['user_id'])):
            followed.append(following.following_id)

    context = {
        'followed': followed,
        'user' : User.objects.get(id=user_id),
        'photos' : m.Photo.objects.filter(user_id=user_id).order_by('-created_at')
    }

    return render(request, 'app_facebro/photos.html', context)

def photo_create(request):
    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')

    if request.method == 'POST' and request.FILES['file']:
        
        myfile = request.FILES['file']
        caption = request.POST['caption']
        user_id = request.session['user_id']

        fs = FileSystemStorage()
        filename = fs.save(str(uuid.uuid4())+'.'+myfile.name.split('.')[-1], myfile)
        uploaded_file_url = fs.url(filename)

        try:
            photo = m.Photo()
            photo.caption = caption
            photo.src = uploaded_file_url
            photo.user_id = user_id
            photo.save()
        except:
            pass

    return redirect('app_facebro:photo', user_id=user_id)

def photo_delete(request, photo_id):
    if 'user_id' not in request.session:
        return redirect('auth_facebro:index')
    
    try:

apps/app_facebro/templates/app_facebro/follower.html
{% extends 'base_facebro/index.html' %} {% load static %} {% block body %}
<div class="container mt-5">
    <div class="row">
        {% include 'app_facebro/sidebar.html' %}
        <div class="col-lg-10">
            <div class="col-lg-12">
                <h1>Follower</h1>
                <hr>
            </div>
            <div class="col-lg-12">
                {% for follow in follower %}
                <div class="media">
                    <img class="mr-3" width="64" src="{{ follow.user.get_avatar.image }}" alt="{{ follow.user.name }}">
                    <div class="media-body">
                        <h5 class="mt-0"><a href="{% url 'app_facebro:timeline' user_id=follow.user.id %}">{% if request.session.user_id == follow.user.id %}You{% else %}{{ follow.user.name }}{% endif %}</a></h5>
                        {% if not follow.user_id in followed %}
                        {% if follow.user_id != request.session.user_id %}
                        <a href="{% url 'app_facebro:follow' email=follow.user.email %}" class="btn btn-sm btn-success">Follow</a>
                        {% endif %}
                        {% else %}
                        <a href="{% url 'app_facebro:unfollow' user_id=follow.user_id %}" class="btn btn-sm btn-warning">Unfollow</a>
                        {% endif %}
                    </div>
                </div>
                <hr>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock %}

apps/app_facebro/templates/app_facebro/following.html
{% extends 'base_facebro/index.html' %} {% load static %} {% block body %}
<div class="container mt-5">
    <div class="row">
        {% include 'app_facebro/sidebar.html' %}
        <div class="col-md-8">
            <div class="col-lg-12">
                <h1>Following</h1>
                <hr>
            </div>
            <div class="col-lg-12">
                {% for follow in followings %}
                <div class="media">
                    <img class="mr-3" width="64" src="{{ follow.following.get_avatar.image }}" alt="{{ follow.following.name }}">
                    <div class="media-body">
                        <h5 class="mt-0"><a href="{% url 'app_facebro:timeline' user_id=follow.following.id %}">{% if request.session.user_id == follow.following.id %}You{% else %}{{ follow.following.name }}{% endif %}</a></h5>
                        {% if follow.following.id != request.session.user_id %}
                        {% if follow.following.id in followed %}
                        <a href="{% url 'app_facebro:unfollow' user_id=follow.following.id %}" class="btn btn-sm btn-warning">Unfollow</a>
                        {% else %}
                        <a href="{% url 'app_facebro:follow' email=follow.following.email %}" class="btn btn-sm btn-success">Follow</a>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>
                <hr> {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/app_facebro/templates/app_facebro/index.html
{% extends 'base_facebro/index.html' %} {% block body %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-4">Facebro</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="{% url 'base_facebro:about' %}" role="button">Learn more</a>
    </div>
</div>
{% endblock %}

apps/app_facebro/templates/app_facebro/search.html
{% extends 'base_facebro/index.html' %} {% block body %} {% load static %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-12">
            <h1>Search :: {{ query }}</h1>
            <hr>
        </div>
        <div class="col-lg-12">
            {% for result in results %}
            <div class="media">
                <img class="mr-3" width="64" src="{{ result.get_avatar.image }}" alt="{{ result.name }}">
                <div class="media-body">
                    <h5 class="mt-0"><a href="{% url 'app_facebro:timeline' user_id=result.id  %}">{{ result.name }}</a></h5>
                    {% if request.session.user_id %}
                        {% if result.id in followed %}
                        <a href="{% url 'app_facebro:unfollow' user_id=result.id %}" class="btn btn-sm btn-warning">Unfollow</a>
                        {% else %}
                        <a href="{% url 'app_facebro:follow' email=result.email %}" class="btn btn-sm btn-success">Follow</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            <hr> {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

apps/app_facebro/templates/app_facebro/sidebar.html
{% load static %}
<div class="col col-lg-2">
        <img src="{{ user.get_avatar.image }}" width="128" class="rounded mx-auto d-block" alt="{{ user.name }}">
    <h3 class="text-center mt-3">{{ user.name }}</h3>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <a href="{% url 'app_facebro:wall' user_id=user.id %}" class="text-secondary"><i class="fa fa-comments"></i> Wall</a>
        </li>
        <li class="list-group-item">
            <a href="{% url 'app_facebro:following' user_id=user.id %}" class="text-secondary"><i class="fa fa-user"></i> Following</a>
        </li>
        <li class="list-group-item">
            <a href="{% url 'app_facebro:follower' user_id=user.id %}" class="text-secondary"><i class="fa fa-user"></i> Follower</a>
        </li>
        <li class="list-group-item">
            <a href="{% url 'app_facebro:photo' user_id=user.id %}" class="text-secondary"><i class="fa fa-photo"></i> Photos</a>
        </li>
        {% if request.session.user_id != user.id %}
        <li class="list-group-item text-center">
            <a href="" class="btn btn-primary btn-lg">FOLLOW</a>
        </li>
        {% endif %}
    </ul>
</div>

apps/app_facebro/templates/app_facebro/timeline.html
{% extends 'base_facebro/index.html' %} {% block body %} {% load static %}
<div class="container mt-5">
    <div class="row">
        {% include 'app_facebro/sidebar.html' %}
        <div class="col-md-10">
            <div class="col-md-8">
                {% if request.session.user_id == user.id or user.id in followed %}
                <form action="{% url 'app_facebro:post_create' user_id=user.id %}" method="POST">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-body">
                            <textarea class="form-control is-valid" placeholder="What's on your mind?" name="html_content" required></textarea>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-sm btn-success">Submit</button>
                        </div>
                    </div>
                </form>
                <hr>
                {% endif %}
                {% for post in posts %}
                <div class="card mb-3 post bg-light">
                    <div class="card-body bg-white">
                        <ul class="list-unstyled">
                            <li class="media">
                                <img class="mr-3" src="{{ post.user.get_avatar.image }}" width="48" alt="{{ post.user.name }}">
                                <div class="media-body">
                                    <small class="text-muted float-right">{{ post.created_at }}</small>
                                    {% if post.user_id == request.session.user_id %}
                                        {% if post.user_id == post.following_id %}
                                        <h5 class="mt-0 mb-1"><a href="{% url 'app_facebro:wall' user_id=post.user.id %}">{{ post.user.name }}</a></h5>
                                        {% else %}
                                        <h5 class="mt-0 mb-1"><a href="{% url 'app_facebro:wall' user_id=post.user.id %}">{{ post.user.name }}</a> > <a href="{% url 'app_facebro:wall' user_id=post.following.id %}">{{ post.following.name }}</a></h5>
                                        {% endif %}
                                        <p class="float-none">{{ post.content }}</p>
                                    {% else %}
                                        {% if post.user_id == post.following_id %}
                                        <h5 class="mt-0 mb-1"><a href="{% url 'app_facebro:wall' user_id=post.user.id %}">{{ post.user.name }}</a></h5>
                                        {% else %}
                                        <h5 class="mt-0 mb-1"><a href="{% url 'app_facebro:wall' user_id=post.user.id %}">{{ post.user.name }}</a> > <a href="{% url 'app_facebro:wall' user_id=post.following.id %}">{{ post.following.name }}</a></h5>
                                        {% endif %}
                                        <p class="float-none">{{ post.content }}</p>
                                    {% endif %}
                                </div>
                            </li>
                        </ul>
                        {% if request.session.user_id == post.user_id or request.session.user_id == post.following_id %}
                        <blockquote class="blockquote mb-0">
                            <div class="row">
                                <div class="col-md-6">
                                    <footer class="blockquote-footer">
                                        <small class="text-muted">
                                            <a href="{% url 'app_facebro:post_delete' post_id=post.id %}" class="text-danger">Delete</a>
                                        </small>
                                    </footer>
                                </div>
                            </div>
                        </blockquote>
                        {% endif %}
                    </div>
                    {% if user.id in followed %}
                    <div class="card-footer">
                        <form action="{% url 'app_facebro:comment_post' post_id=post.id %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control" name="html_content" placeholder="Enter comment">
                            </div>
                        </form>
                    </div>
                    {% else %}
                    <hr>
                    {% endif %}
                    {% if post.post_comment.all %}
                    <ul class="list-unstyled p-3">
                        {% for comment in post.get_comment %}
                        <li class="media mt-2">
                            <img class="mr-3" src="{{ comment.user.get_avatar.image }}" width="32" alt="Generic placeholder image">
                            <div class="media-body">
                                <small class="text-muted float-right">{{ comment.created_at }}</small>
                                <h6 class="mt-0 mb-1"><a href="{% url 'app_facebro:wall' user_id=comment.user.id %}">{{ comment.user.name }}</a></h6>
                                <p class="float-none">{{ comment.content }}</p>
                                {% if request.session.user_id == comment.user.id %}
                                <footer class="blockquote-footer float-left">
                                    <a href="{% url 'app_facebro:comment_delete' comment_id=comment.id %}" class="text-danger">Delete</a>
                                </footer>
                                {% endif %}
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div> {% endfor %}
            </div>
        </div>
    </div>
    {% endblock %}

apps/app_facebro/templates/app_facebro/wall.html
{% extends 'base_facebro/index.html' %} {% block body %} {% load static %}
<div class="container mt-5">
    <div class="row">
        {% include 'app_facebro/sidebar.html' %}
        <div class="col-md-10">
            <div class="col-md-8">
                {% if request.session.user_id == user.id or user.id in followed %}
                <form action="{% url 'app_facebro:post_create' user_id=user.id %}" method="POST">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-body">
                            <textarea class="form-control is-valid" placeholder="What's on your mind?" name="html_content" required></textarea>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-sm btn-success">Submit</button>
                        </div>
                    </div>
                </form>
                <hr>
                {% endif %}
                {% if posts %}
                {% for post in posts %}
                <div class="card mb-3 post bg-light">
                    <div class="card-body bg-white">
                        <ul class="list-unstyled">
                            <li class="media">
                                <img class="mr-3" src="{{ post.user.get_avatar.image }}" width="48" alt="{{ post.user.name }}">
                                <div class="media-body">
                                    <small class="text-muted float-right">{{ post.created_at }}</small>
                                    {% if post.user_id == post.following_id %}
                                    <h5 class="mt-0 mb-1"><a href="{% url 'app_facebro:wall' user_id=post.user.id %}">{{ post.user.name }}</a></h5>
                                    {% else %}
                                    <h5 class="mt-0 mb-1"><a href="{% url 'app_facebro:wall' user_id=post.user.id %}">{{ post.user.name }}</a> > <a href="{% url 'app_facebro:wall' user_id=post.following.id %}">{{ post.following.name }}</a></h5>
                                    {% endif %}
                                    <p class="float-none">{{ post.content }}</p>
                                </div>
                            </li>
                        </ul>
                        {% if request.session.user_id == post.user_id or request.session.user_id == post.following_id %}
                        <blockquote class="blockquote mb-0">
                            <div class="row">
                                <div class="col-md-6">
                                    <footer class="blockquote-footer">
                                        <small class="text-muted">
                                            <a href="{% url 'app_facebro:post_delete' post_id=post.id %}" class="text-danger">Delete</a>
                                        </small>
                                    </footer>
                                </div>
                            </div>
                        </blockquote>
                        {% endif %}
                    </div>
                    {% if user.id in followed %}
                    <div class="card-footer">
                        <form action="{% url 'app_facebro:comment_post' post_id=post.id %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control" name="html_content" placeholder="Enter comment">
                            </div>
                        </form>
                    </div>
                    {% else %}
                    <hr>
                    {% endif %}
                    {% if post.post_comment.all %}
                    <ul class="list-unstyled p-3">
                        {% for comment in post.get_comment %}
                        <li class="media mt-2">
                            <img class="mr-3" src="{{ comment.user.get_avatar.image }}" width="32" alt="Generic placeholder image">
                            <div class="media-body">
                                <small class="text-muted float-right">{{ comment.created_at }}</small>
                                <h6 class="mt-0 mb-1"><a href="{% url 'app_facebro:wall' user_id=comment.user.id %}">{{ comment.user.name }}</a></h6>
                                <p class="float-none">{{ comment.content }}</p>
                                {% if request.session.user_id == comment.user.id %}
                                <footer class="blockquote-footer float-left">
                                    <a href="{% url 'app_facebro:comment_delete' comment_id=comment.id %}" class="text-danger">Delete</a>
                                </footer>
                                {% endif %}
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div> {% endfor %} {% else %}
                <div class="alert alert-warning mt-3" role="alert">
                    {% if request.session.user_id == user.id %}
                    <h4 class="alert-heading">Dude!!!</h4>
                    <p class="mb-0">You has no post</p>
                    {% else %}
                    <h4 class="alert-heading">Sorry!!!</h4>
                    <p class="mb-0">This user has no post</p>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock %}