Facebro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('auth/', include('apps.auth_facebro.urls', namespace='auth_facebro')),
    path('base/', include('apps.base_facebro.urls', namespace='base_facebro')),
    path('', include('apps.app_facebro.urls', namespace='app_facebro')),
    path('admin/', admin.site.urls),
]

apps/auth_facebro/urls.py
from django.urls import path
from . import views

app_name = 'auth_facebro'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('signout', views.signout, name='signout'),
]

apps/auth_facebro/models.py
from django.db import models

class User(models.Model):
    
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=64, unique=True)
    password = models.CharField(max_length=64)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def get_avatar(self):
        return self.user_profile.get(is_active=1)

class Profile(models.Model):
    
    image = models.CharField(max_length=64, null=True)
    is_active = models.IntegerField()

    user = models.ForeignKey(User, related_name='user_profile', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/auth_facebro/views.py
import bcrypt
from django.shortcuts import render, redirect
from django.contrib import messages
from . import models as m
from . import utilities as util

def index(request):
    if 'user_id' in request.session:
        return redirect('app_facebro:timeline', user_id=request.session['user_id'])
    return render(request, 'auth_facebro/index.html')

def signup(request):

    if 'user_id' in request.session:
        return redirect('app_facebro:timeline', user_id=request.session['user_id'])

    if request.method == 'POST':

        request.session['error'] = ''

        name = request.POST['html_name']
        email = request.POST['html_email']
        password = request.POST['html_password']
        confirm = request.POST['html_confirm']

        errors = []

        errors += util.is_blank('name', name)
        errors += util.is_blank('email', email)
        errors += util.is_blank('password', password)
        errors += util.is_blank('confirm', confirm)

        if password != confirm:
            errors.append('Password doesn\'t match')
        if len(password) < 6:
            errors.append('Password too short')
        if not util.EMAIL_REGEX.match(email):
            errors.append('Email formated error')

        for error in errors:
            messages.error(request, error)

        request.session['error'] = 'signup'

        if len(errors) == 0:

            try:
                m.User.objects.get(email=email)
                messages.error(request, 'Email already exist')
            except:
                user = m.User()
                user.name = name
                user.email = email
                user.password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
                user.save()

                request.session['user_id'] = user.id
                request.session['name'] = user.name

                return redirect('app_facebro:index')

    return render(request, 'auth_facebro/index.html')

def signin(request):

    if 'user_id' in request.session:
        return redirect('app_facebro:timeline', user_id=request.session['user_id'])

    if request.method == 'POST':

        request.session['error'] = ''

        email = request.POST['html_email']
        password = request.POST['html_password']

        errors = []

        errors += util.is_blank('email', email)
        errors += util.is_blank('password', password)

        request.session['error'] = 'signin'

        try:
            user = m.User.objects.get(email=email)
            
            if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
                request.session['user_id'] = user.id
                request.session['name'] = user.name
                return redirect('app_facebro:timeline', user_id=request.session['user_id'])
            else:
                messages.error(request, 'Password not match')

        except:
            messages.error(request, 'Invalid login')
    
    return render(request, 'auth_facebro/index.html')

def signout(request):
    request.session.clear()
    return redirect('auth_facebro:index')

apps/auth_facebro/templates/auth_facebro/index.html
{% extends 'base_facebro/index.html' %} {% block body %}
<div class="container mt-5">
    <div class="row justify-content-around">
        <div class="col-4">
            <h3>Already member</h3>
            <hr>
            <form action="{% url 'auth_facebro:signin' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="email_signin">Email address</label>
                    <input type="email" name="html_email" class="form-control" id="email_signin" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="password_signin">Password</label>
                    <input type="password" name="html_password" class="form-control" id="password_signin" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-outline-secondary">Signin</button>
            </form>
            {% if request.session.error == 'signin' %}
                {% include 'base_facebro/errors.html' %}
            {% endif %}
        </div>
        <div class="col-4">
            <h3>New member</h3>
            <hr>
            <form action="{% url 'auth_facebro:signup' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="email_signup">Name</label>
                    <input type="text" name="html_name" class="form-control" id="email_signup" placeholder="Enter fullname">
                </div>
                <div class="form-group">
                    <label for="email_signup">Email address</label>
                    <input type="email" name="html_email" class="form-control" id="email_signup" aria-describedby="emailHelp" placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="password_signup">Password</label>
                    <input type="password" name="html_password" class="form-control" id="password_signup" placeholder="Password">
                </div>
                <div class="form-group">
                    <label for="confirm_password_signup">Confirm Password</label>
                    <input type="password" name="html_confirm" class="form-control" id="confirm_password_signup" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-outline-secondary">Signup</button>
            </form>
            {% if request.session.error == 'signup' %}
                {% include 'base_facebro/errors.html' %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}