Facebro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('auth/', include('apps.auth_facebro.urls', namespace='auth_facebro')),
    path('base/', include('apps.base_facebro.urls', namespace='base_facebro')),
    path('', include('apps.app_facebro.urls', namespace='app_facebro')),
    path('admin/', admin.site.urls),
]

apps/app_facebro/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'app_facebro'

urlpatterns = [
    path('', views.index, name='index'),
    path('timeline', views.timeline, name='timeline'),
    path('user/<int:user_id>/wall', views.wall, name='wall'),
    path('settings', views.setting, name='setting'),
    path('profile/update', views.profile_update, name='profile_update'),
    path('profile/upload', views.profile_upload, name='profile_upload'),
    path('password/update', views.password_update, name='password_update'),
    path('user/<int:user_id>/post', views.post_create, name='post_create'),
    path('post/<int:post_id>/delete', views.post_delete, name='post_delete'),
    path('user/<int:user_id>/following', views.following, name='following'),
    path('user/<str:email>/follow', views.follow, name='follow'),
    path('user/<str:user_id>/unfollow', views.unfollow, name='unfollow'),
    path('user/<int:user_id>/follower', views.follower, name='follower'),
    path('user/<int:user_id>/photos', views.photo, name='photo'),
    path('photo/create', views.photo_create, name='photo_create'),
    path('photo/<int:photo_id>/delete', views.photo_delete, name='photo_delete'),
    path('search', views.search, name='search'),
    path('results/<str:query>', views.results, name='results'),
    path('comment/<int:post_id>/post', views.comment_post, name='comment_post'),
    path('comment/<int:comment_id>/delete', views.comment_delete, name='comment_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/auth_facebro/urls.py
from django.urls import path
from . import views

app_name = 'auth_facebro'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('signout', views.signout, name='signout'),
]

apps/base_facebro/urls.py
from django.urls import path
from . import views

app_name = 'base_facebro'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

apps/base_facebro/models.py
from django.db import models

# Create your models here.

apps/base_facebro/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'base_facebro/index.html')

def about(request):
    return render(request, 'base_facebro/about.html')

apps/base_facebro/templates/base_facebro/about.html
{% extends 'base_facebro/index.html' %} {% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1>About</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe similique doloremque aliquam, iste praesentium commodi ea nesciunt omnis modi quam laboriosam sit voluptates odit? Tenetur incidunt facilis laudantium sint repudiandae?</p>
        </div>
    </div>
</div>
{% endblock %}

apps/base_facebro/templates/base_facebro/errors.html
{% if messages %} 
<hr>
{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %} {% endif %}

apps/base_facebro/templates/base_facebro/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-muted">&copy; 2017-2018</small>
            </div>
            <div class="col-6 col-md">
                <h5>Features</h5>
                <ul class="list-unstyled text-small">
                    <li>
                        <a class="text-muted" href="#">Cool stuff</a>
                    </li>
                    <li>
                        <a class="text-muted" href="#">Random feature</a>
                    </li>
                    <li>
                        <a class="text-muted" href="#">Team feature</a>
                    </li>
                    <li>
                        <a class="text-muted" href="#">Stuff for developers</a>
                    </li>
                    <li>
                        <a class="text-muted" href="#">Another one</a>
                    </li>
                    <li>
                        <a class="text-muted" href="#">Last time</a>
                    </li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Resources</h5>
                <ul class="list-unstyled text-small">
                    <li>
                        <a class="text-muted" href="#">Resource</a>
                    </li>
                    <li>
                        <a class="text-muted" href="#">Resource name</a>
                    </li>
                    <li>
                        <a class="text-muted" href="#">Another resource</a>
                    </li>
                    <li>
                        <a class="text-muted" href="#">Final resource</a>
                    </li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>About</h5>
                <ul class="list-unstyled text-small">
                    <li>
                        <a class="text-muted" href="#">Team</a>
                    </li>
                    <li>
                        <a class="text-muted" href="#">Locations</a>
                    </li>
                    <li>
                        <a class="text-muted" href="#">Privacy</a>
                    </li>
                    <li>
                        <a class="text-muted" href="#">Terms</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

apps/base_facebro/templates/base_facebro/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'base_facebro/css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'base_facebro/css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'base_facebro/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'base_facebro/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'base_facebro/css/styles.css' %}">
    <title>Facebro</title>
</head>

<body>
    {% include 'base_facebro/navbar.html' %} {% block body %} {% endblock %} {% include 'base_facebro/footer.html' %}

    <script src="{% static 'base_facebro/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'base_facebro/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'base_facebro/js/scripts.js' %}"></script>
</body>

</html>

apps/base_facebro/templates/base_facebro/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'app_facebro:index' %}">FACEBRO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link my-2 my-sm-0" href="{% url 'base_facebro:about' %}">About</a>
                </li>
                {% if request.session.name %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'app_facebro:timeline' %}">Timeline
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <i class="fa fa-user-circle"></i> {{ request.session.name }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'app_facebro:wall' user_id=request.session.user_id %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'app_facebro:setting' %}">Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'auth_facebro:signout' %}">Signout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="btn btn-primary my-2 my-sm-0" href="{% url 'auth_facebro:index' %}"><i class="fa fa-user"></i> Join</a>
                </li>
                {% endif %}
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'app_facebro:search' %}" method="POST">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" name="html_query" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>